package com.jobmatcher.backend.ai;

import com.jobmatcher.backend.dto.response.MatchResponse;
import com.jobmatcher.backend.entity.Job;
import com.jobmatcher.backend.entity.Resume;
import com.jobmatcher.backend.exception.JobNotFoundException;
import com.jobmatcher.backend.exception.UserNotFoundException;
import com.jobmatcher.backend.repository.JobRepository;
import com.jobmatcher.backend.repository.ResumeRepository;
import com.jobmatcher.backend.service.MatchService;
import lombok.RequiredArgsConstructor;
import org.jetbrains.annotations.NotNull;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@RequiredArgsConstructor
public class AiServiceImpl implements AiService {

    private final ResumeRepository resumeRepository;
    private final JobRepository jobRepository;
    private final MatchService matchService;
    private final PromptBuilder promptBuilder;
    private final GeminiClient geminiClient;

    @Override
    public AiResponse analyzeResume(Long resumeId, Long jobId) throws Exception {

        // Fetch Resume
        Resume resume = resumeRepository.findById(resumeId)
                .orElseThrow(() ->
                        new UserNotFoundException("Resume not found"));

        // Fetch Job
        Job job = jobRepository.findById(jobId)
                .orElseThrow(() ->
                        new JobNotFoundException("Job not found"));

        // Existing matching algorithm
        MatchResponse match =
                matchService.matchResumeWithJob(resumeId, jobId);

        // Build prompt
        String prompt = promptBuilder.buildPrompt(
                resume.getExtractedText(),
                job.getDescription(),
                match.getMatchPercentage()
        );

        // Call Gemini
        String aiText = geminiClient.generate(prompt);

        // Build response
        AiResponse response = getAiResponse(match, aiText);

        return response;
    }

    @NotNull
    private static AiResponse getAiResponse(MatchResponse match, String aiText) {
        AiResponse response = new AiResponse();

        response.setMatchPercentage(match.getMatchPercentage());

        response.setSummary(aiText);

        response.setStrengths(match.getMatchedSkills());

        response.setMissingSkills(match.getMissingSkills());

        response.setImprovements(
                List.of(
                        "Generated by Gemini AI. Review the summary above."
                )
        );

        response.setInterviewQuestions(
                List.of(
                        "Refer to the AI-generated summary for suggested interview topics."
                )
        );
        return response;
    }
}